### ISSUE TITLE
How to effectively use .dockerignore

### ISSUE THREAD

**Issue by Izabela17** [hgop/syllabus-2020#10]
How to update the already build docker image so it does not contain files mentioned in the dockerignore?
Can we update the already shared docker image in the docker repository so it does not have files mentioned in dockerignore?
A bit lost about how that works!  
Thanks!

**Comment by Fanneyyy** [comment]
## What does docker ignore do?
The `.dockerignore` file is used to exclude files when we copy files from the current directory into the docker image. So e.g. if we have files in our directory like so:
```bash
.
├── node_modules
├── public
│   ├── ...
│   └── index.html
├── src
│   ├── ...
│   ├── index.tsx
│   └── App.tsx
├── .dockerignore
├── .gitignore
├── Dockerfile
├── tsconfig.json
├── package-lock.json
└── package.json
```
And we do this command in our Dockerfile: `COPY . .` (copy my current directory into the docker image) the command will ignore all files/folders listed in the `.dockerignore` file, e.g. node_modules folder and the Dockerfile itself.

## Why do we do this?
There are multiple reason for using docker ignore. E.g. if we want to minimize the size of the docker image, we don't want any extra files that we don't need and generally we just don't want to copy anything that is not needed (we are not super worried about this during this course). More advanced dockerfiles will often delete files that are only needed for building artefacts and not for running the actual artefact.
In our case we build our dependencies when we build the docker image, (RUN npm install) which generates node_modules in the image, then when we COPY all files from our current directory to the image we don't want to include the local node_modules folder because it could be outdated or conflicting in some way. We want the docker image to be a clean environment.

## We already built and pushed an image with files we don't want to include
Just add the `.dockerignore` next to your Dockerfile, build the image again, tag and push it again. It will overwrite the old image, you can push as often as you like.

Hope this answers your question 😊
