### ISSUE TITLE
microk8s stopped running - The Service snap.microk8s.daemon-apiserver is failing

### ISSUE THREAD

**Issue by Izabela17** [hgop/syllabus-2020#28]
### **Expected behavior**
microk8s running without any problem and the Kubernetes cluster is up and running. 
### **Current behavior**
After pushing changes onto connect-four-client main branch the microk8s stopped working what resolved in the app being down.
### **Context**
![image](https://user-images.githubusercontent.com/42979279/100864398-d5fb9580-348d-11eb-8719-cc3e4eb58325.png)
The Service snap.microk8s.daemon-apiserver is failing
### **Failure information**
Trying to spin up the snap.microk8s.daemon-apiserver with sudo command gave this error:
![image](https://user-images.githubusercontent.com/42979279/100864764-5b7f4580-348e-11eb-9511-e0df7714ab70.png)
I´m guessing the key is incorrect and is due to the server connection with the client somehow. How do I update the k8s.yaml.template so pushing from both repositories is possible? (just a guess could be something completely different that gave this error)

**Comment by ingi17** [comment]
I'm having the same issue
![image](https://user-images.githubusercontent.com/34063026/100878029-89ba5080-34a1-11eb-81ab-d35a4e03fcb8.png)

Upon further inspection last night I found that my aws instance was out of space
![image](https://user-images.githubusercontent.com/34063026/100878160-b3737780-34a1-11eb-83bb-3a3ac21ccf59.png)
With most of the space being used by /snap/microk8s/common/var/. I cleared old images as per #23 and now have some 400Mib left.
From my previous issue at #26 I've found that my kubectl pods are getting filled by httpbin pods all with the same tag and all evicted. Although I'm unable to screenshot it now due to microk8s being down, is that possibly the root of the problem? Surely I've done something wrong in my setup.

**Comment by Izabela17** [comment]
Exactly the same problem @ingi17 I'm guessing that our set up was correct but it was made for t3 AWS instance that just have bigger memory therefore there are 2 options - 1.somehow we have to limit the space that is taken by the cluster (I have also followed #23 but the problem is still there. And the cluster for us was filling with the client images with the same tag). 2. Get a bigger AWS instance. Let's hope it will get resolved! :)

**Comment by ironpeak** [comment]
https://github.com/hgop/syllabus-2020/issues/29
