### ISSUE TITLE
server acceptance test

### ISSUE THREAD

**Issue by thoalr** [hgop/syllabus-2020#31]
The acceptance test in the circleci pipeline fails.
It gets a response 
```
response = requests.get(config.API_URL + "/status")
assert "Running" == response.text
E       AssertionError: assert 'Running' == '<html>\r\n<h...\n</html>\r\n'
E         + Running
E         - <html>
E         - <head><title>502 Bad Gateway</title></head>
E         - <body>
E         - <center><h1>502 Bad Gateway</h1></center>
E         - <hr><center>nginx/1.19.0</center>
E         - </body>
E         - </html>
```
This is most likely because there is not enough time between deploying the acceptance server allowing it enough time to go online and and running the test.

The acceptance test does work if it is run a couple minutes after deploying the acceptance server.

What can I do to fix this. Currently I have to manually rerun the workflow from failed.

**Comment by ironpeak** [comment]
I recommend you do this:

https://github.com/hgop/syllabus-2020/issues/29

The disk pressure on the instances you create with your education account can slow down the deployment, due to internal cleanup commands that need to free space before downloading the new image.

If the problem persists after that add a sleep before calling the acceptance tests to give the pod time to start up.
