### ISSUE TITLE
Test_app_logic - difficulties with mocking 

### ISSUE THREAD

**Issue by Izabela17** [hgop/syllabus-2020#39]
**### Issue**
Unable to mock JoinGameRequest or Get game 
**### What happening now**
![image](https://user-images.githubusercontent.com/42979279/101195028-b95e8980-3656-11eb-827c-d4dbdbb21fd2.png)
### **Bug**
![image](https://user-images.githubusercontent.com/42979279/101195158-ec088200-3656-11eb-9858-35031cfcf07b.png)

Have also tried not mocking JoinGameRequest and using a helper function that creates the initial game. Then I always get "Game not found" exception. How do I mock the initial game so I can use it successfully in this function?

**Comment by holmar18** [comment]
I tried executing the code and got the same error, for me to fix the error patch and input variables had to be in same order to map them correctly i guess.

@patch("connect4.database.get_game")
@patch("connect4.database.get_players")
@patch("connect4.tokens.generate_token")
@patch("connect4.database.add_player_to_game")
@patch("connect4.models.JoinGameRequest")

def test_join_gamme(mock_JoinGameRequest, mock_add_player_to_game, mock_generate_token, mock_get_players, mock_get_game):

Then there was some kind of recursion error that could be fixed by changing the mock_joinGameRequest.return_value not side_effect

**Comment by Izabela17** [comment]
Ok, thanks I had no idea that the order of the @patch and how you give it into the function matters! I can at least start debugging now :D
